name: maze_runner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame_audio: ^2.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/dungeon_tileset.png
    - assets/images/soldier.png
    - assets/images/orc.png
    - assets/images/hearts.png
    - assets/fonts/PublicPixel-rv0pA.ttf
    - assets/audio/background_music.mp3
    - assets/audio/swing.wav

  fonts:
    - family: PublicPixel
      fonts:
        - asset: assets/fonts/PublicPixel-rv0pA.ttf

  uses-material-design: true